# Generated by Django 3.2.8 on 2021-10-20 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=2000)),
                ('veg_nonveg', models.CharField(choices=[('VEG', 'VEG'), ('NONVEG', 'NONVEG')], default='', max_length=50)),
                ('price', models.CharField(choices=[('3000', '$$$'), ('1500', '$$'), ('800', '$')], default='$$$', max_length=30)),
                ('dine_in', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='', max_length=200)),
                ('delivery', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='Yes', max_length=200)),
                ('contact', models.CharField(default='XXXXX-XXXXX', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tag',
            field=models.ManyToManyField(blank=True, to='restaurant.Tag'),
        ),
    ]
